### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RickHaleParker**
Added Schematic for Bosch CF160 version in Doc folder.

### CODE REVIEW

**Comment by vtl** [comment]
No U3 on schematics? Mentioned, but not placed.

**Comment by RickHaleParker** [comment]
Opp! Forgot to delete reference to U3. Uploaded corrected file.

**Comment by vtl** [comment]
I'm going to squash the commits before merge. What commit message would you like to put? Or squash & edit yourself if you prefer.

**Comment by RickHaleParker** [comment]
Squash everything but my original comment.  The rest will serve no purpose from here on.

**Pull request merged**
